### ISSUE TITLE
URLs sent to hipchat don't appear as links.

### ISSUE THREAD

**Issue by pzearfoss** [bitrise-io/steps-hipchat#9]
Not sure if it's a bug or if I'm just doing it wrong, but when I send a url to our hipchat room, it doesn't appear as a link (not clickable)

![image](https://cloud.githubusercontent.com/assets/583236/12455386/79a9eb5e-bf69-11e5-94de-817668fde427.png)

Here is what our step looks like in bitrise:
![image](https://cloud.githubusercontent.com/assets/583236/12455426/a5bade74-bf69-11e5-83a4-28f9092a8e55.png)

**Comment by viktorbenei** [comment]
We'll check it and fix the step if we can - we believe that HipChat might expect a Markdown style link through the API, instead of just a pure link text, but we'll check&fix it if possible.

**Comment by pzearfoss** [comment]
Is it something I can format differently in the build step? It's just a static URL.

**Comment by viktorbenei** [comment]
Not in the build step, but in the "message" parameter of the HockeyApp step. The markdown equivalent of a link `$A_LINK` is `[$A_LINK]($A_LINK)`

**Comment by jsinh** [comment]
@pzearfoss @viktorbenei - The HIP chat message current being sent is expected to be in HTML format. So try to use the LINK with

```
<a href="#" />
```

Not tested but almost sure that would make it better!

**Comment by viktorbenei** [comment]
@jsinh is most likely right, sorry @pzearfoss it's been quite some time we last used HipChat (we use Slack these days everywhere). Good news is, there will be an option to change the format, thanks to @jsinh ;) - https://github.com/bitrise-io/steps-hipchat/pull/10

**Comment by godrei** [comment]
In new version 3.0.1, we added a new input: `message_format` (https://github.com/bitrise-io/steps-hipchat/releases/tag/3.0.1).
@pzearfoss by default `message_format ` is html, so you can use href tag in `message` and `message_on_error` as well (ex: <a href="http://www.google.com">Visit Google</a>).
